if (InstallPrefix)
  find_path(GMP_INCLUDE_DIRECTORY gmp.h gmpxx.h PATHS ${InstallPrefix}/include NO_DEFAULT_PATH)
  find_library(GMP_LIBRARY gmp PATHS ${InstallPrefix}/lib NO_DEFAULT_PATH)
  find_library(GMPXX_LIBRARY gmpxx PATHS ${InstallPrefix}/lib NO_DEFAULT_PATH)

  find_path(ZMQ_INCLUDE_DIRECTORY zmq.h PATHS ${InstallPrefix}/include NO_DEFAULT_PATH)
  if (WIN32)
    find_library(ZMQ_LIBRARY zmq.dll PATHS ${InstallPrefix}/lib NO_DEFAULT_PATH)
    find_library(SODIUM_LIBRARY sodium PATHS ${InstallPrefix}/lib NO_DEFAULT_PATH)
  else()
    find_library(ZMQ_LIBRARY zmq PATHS ${InstallPrefix}/lib NO_DEFAULT_PATH)
    find_library(SODIUM_LIBRARY sodium PATHS ${InstallPrefix}/lib NO_DEFAULT_PATH)
  endif()
else()
  find_path(GMP_INCLUDE_DIRECTORY gmp.h gmpxx.h)
  find_library(GMP_LIBRARY gmp)
  find_library(GMPXX_LIBRARY gmpxx)

  find_path(ZMQ_INCLUDE_DIRECTORY zmq.h)
  if (WIN32)
    find_library(ZMQ_LIBRARY zmq.dll)
	find_library(SODIUM_LIBRARY sodium)
  else()
    find_library(ZMQ_LIBRARY zmq)
    find_library(SODIUM_LIBRARY sodium)
  endif()
endif()
